project:
  type: website

website:
  google-analytics: G-9Q0VSK0VJF
  site-url: https://stat131a.berkeley.edu/summer-2025/
  sidebar:
    style: docked
    title: "Stat 131a"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat131a/summer-2025
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: assignments.qmd
        text: HW and Labs
      - href: project.qmd
        text: Project
      - href: syllabus.qmd
        text: Syllabus
      - href: staff.qmd
        text: Staff
      - href: calendar.qmd
        text: Google Calendar

          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
    include-in-header:
      file: siteimprove.html


include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "favicon.ico" />
