project:
  type: website

website:
  google-analytics: G-9Q0VSK0VJF
  site-url: https://stat131a.berkeley.edu/summer-2025/
  sidebar:
    style: docked
    title: "Stat 131a"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat131a/summer-2025
    contents:
      - href: index.qmd
        text: Main

format:
  html:
    theme: cosmo
    css: assets/styles-alt.scss
    toc: true
    include-in-header:
      file: siteimprove.html


include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "favicon.ico" />
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

